# Basic
title: 肤浅的大西瓜
subtitle:
welcome_message: <a href="https://zhaoyuivan.github.io/#blog" target="_blank">来互相伤害呀- -`</a>
description: iOS码农
creator: <a href="https://zhaoyuivan.github.io/#blog">@zhaoyuivan</a>

url: "https://zhaoyuivan.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/zhaoyuivan'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate, jekyll-plantuml]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
#    disqus: vno-jekyll
#     duoshuo:
    
# Social
social:
#    weibo: onevcat
    github: zhaoyuivan
#    twitter: onevcat
#    gplus: 107108267983477358170
    mail: zhaoyuivanzhao@126.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
